##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow will delete the a DEV track
#
##############################################################################
name: delete dev-track

env:
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  TRACK_DIR: instruqt-tracks

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

jobs:
  GetTrackSlugs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: Install yq Package
      uses: ./.github/actions/install-yq
    
    - name: Create Matrix Data
      run: echo "TRACKS=$(yq -o j $TRACK_DIR/track-slugs.yml | jq tostring | sed -e 's/^"//' -e 's/"$//')" >> $GITHUB_ENV

    - id: set-matrix
      run: echo "::set-output name=matrix::${{ env.TRACKS }}"

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
  DeleteDevTracks:
     runs-on: ubuntu-latest
     if: ${{ needs.GetTrackSlugs.outputs.matrix != '[]' && needs.GetTrackSlugs.outputs.matrix != '' }}
     needs: GetTrackSlugs
     strategy:
       matrix: ${{ fromJson(needs.GetTrackSlugs.outputs.matrix) }}
     steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Delete dev track
        uses: ./.github/actions/track-delete
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}-dev
          
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deleting the dev version of ${{ matrix.tracks.slug }}-dev  
        


